apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sallowcertaintypeservice
spec:
  crd:
    spec:
      names:
        kind: K8sAllowCertainTypeService
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowed_svc_type:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowcertaintypeservice

        violation[{"msg": msg}] {
          svc := input.review

          svc.kind.kind == "Service"

          matched = [ match | match := input.parameters.allowed_svc_type[_] == svc.object.spec.type ]

          not any(matched)

          msg := sprintf("service \"%v\" has an disallowed service type <%v>, allowed types are <%v>", [svc.object.metadata.name, svc.object.spec.type, input.parameters.allowed_svc_type])
        }