apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MyFirstTemplate<id>
metadata:
  name: pod-violation-<id>
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "user-<id>"